# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='lat_coordinate',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='long_coordinate',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='media_url',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='street_address',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='source_created_at',
            field=models.DateTimeField(default='2000-01-01T00:00:00+0000'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.CharField(max_length=1024),
        ),
    ]
